	var L_URLHREF1 = "http://www.microsoft.com/isapi/redir.dll?Prd=WMT&Sbp=WMP&Plcid=0x0804&Pver=3&Os=Win&Over=5&Olcid=0x0804&Clcid=0x0804&Ar=Home";
	var L_URLTEXT1 = "Windows Media Player";
	var L_URLHREF2 = "http://www.microsoft.com/isapi/redir.dll?Prd=WMT&Ar=HM";
	var L_URLTEXT2 = "WindowsMedia.com";
	var L_URLHREF3 = "http://www.microsoft.com/isapi/redir.dll?Prd=WMT&Ar=MSHM";
	var L_URLTEXT3 = "Microsoft";
	
